### ISSUE TITLE
Options combinations

### ISSUE THREAD

**Issue by Sim4n6** [e1abrador/sub.Monitor#1]
This is a very interesting python script . I really love it . I was working on something similar.... 
bur one detail, there is a bit of confusing regarding the options they could be more condensed for instance no need for --dump and --dumpall and some options combinations are not possible.

**Comment by Sim4n6** [comment]
I meant 


```python3
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--add", help="Domain to scan")                                               # 1 - add a domain to scan 
    parser.add_argument("--out-scope", help="File with out-of-scope domains")
    parser.add_argument("--file", help="File with known subdomains")                          
    parser.add_argument("-d", help="Domain to scan")                                                     # 1 - add a domain to scan too ? 
    parser.add_argument("-h", type=int, help="Hours between scans")
    parser.add_argument(
        "--dump", action="store_true", help="Dump all subdomains for a specific domain" # 2 - there is --list too 
    )
    parser.add_argument(
        "--list", action="store_true", help="List all root domains in the database"
    )
    parser.add_argument("-df", help="File with domains to scan")                                   # a bit confused 
    parser.add_argument(
        "--inscope", action="store_true", help="Dump only in-scope domains"
    )
    parser.add_argument(
        "--notinscope", action="store_true", help="Dump only out-of-scope domains"                 # how about --outofscope
    )
    parser.add_argument(
        "--dumpall", action="store_true", help="Dump all subdomains with their details"
    )
    parser.add_argument(
        "--info", action="store_true", help="Show discovery date for subdomains"
    )
    parser.add_argument(
        "-help",
        "-?",
        action="help",
        default=argparse.SUPPRESS,
        help="Show this help message and exit",
    )
    args = parser.parse_args()
```

**Comment by e1abrador** [comment]
Hello, 
Thanks for the feedback!
``--dumpall`` is a flag I was using for debugging purposes when dumping the subdomains from the database, I should remove it since it has no real use on this version, and in the next commits, I will remove it.
``--add`` flag is used to add manually subdomains on the database, and ``-d`` is used when starting the monitoring process. I should rewrite the description on each flag, didn't really notice that.

Also ``--notinscope`` flag I know is not working (same as ``--dumpall``), gotta solve it on the next update ; ).

In any case, in order to avoid any problems in the current version I recommend reading carefully the README.md file, following that guide no problems should appear.

**Comment by Sim4n6** [comment]
Thx I read the code and I am already running thee script. I hope my suggestions helped have a nice evening

**Comment by e1abrador** [comment]
> Thx I read the code and I am already running thee script. I hope my suggestions helped have a nice evening

I also noticed that when using ``-h`` there's a problem when showing all the flags supported by the script (aka --help panel), gotta rename it on the next update.

If you would like to implement any functionality on the script let me know on a new issue or on a Pull Request. I'll be happy to evaluate the implementation.

Same! Have a nice evening!

**Comment by Sim4n6** [comment]
I will I promise.
